DONGTAN/dongtanjumak/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from dongtanjumak.views import HomeView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(),name='home'),
    path('homepage/',include('homepage.urls'), name='homepage'),
]

DONGTAN/homepage/urls.py
from django.urls import path, re_path
from homepage.views import *

app_name='homepage'

urlpatterns= [
	path('intro/',IntroTV.as_view(),name='intro'),
	path('dish/',DishLV.as_view(),name='dish'),
	re_path(r'^dish/(?P<pk>\d+)/$',DishDV.as_view(),name='dish_detail'),
	path('photo/',PhotoTV.as_view(),name='photo'),



]

DONGTAN/homepage/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Menu(models.Model):
	name=models.CharField('NAME',max_length=50)
	price=models.IntegerField('PRICE')
	description=models.TextField('DESCRIPTION',max_length=100, blank=True, help_text='explanation for food')

	class Meta:
		verbose_name='menu'
		verbose_name_plural='menus'
		db_table='dongtanjumak_menu'

	

DONGTAN/dongtanjumak/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
	template_name='home.html'

DONGTAN/homepage/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from homepage.models import Menu

class IntroTV(TemplateView):
	template_name='homepage/intro.html'

class DishLV(ListView):
	model=Menu
	template_name='homepage/menu_all.html'
	context_object_name='menus'


class DishDV(DetailView):
	model=Menu
	template_name='homepage/menu_detail.html'

class PhotoTV(TemplateView):
	template_name='homepage/photo.html'

DONGTAN/homepage/templates/homepage/intro.html
{% extends "base.html" %}
{% block title %}intro.html{% endblock %}
{% load staticfiles %}
{% block content %}
<div>
	<span>
Intro</span>
</div>
{% endblock %}

DONGTAN/homepage/templates/homepage/menu_all.html
{% extends "base.html" %}
{% block title %}menu_all.html{% endblock %}
{% block content %}

Menu

{% endblock %}

DONGTAN/homepage/templates/homepage/photo.html
{% extends "base.html" %}
{% block title %}photo.html{% endblock %}
{% block content %}

Photo

{% endblock %}

DONGTAN/templates/base.html
<!DOCTYPE html>
<html>
<head>
	<title>
		{% block titie %}BASE{% endblock %}
	</title>
	{% load staticfiles %}
	<link rel="stylesheet"  type="text/css" href="{% static 'css/base.css' %}" />
	<link rel="stylesheet" type="text/css" href="{% block extrastyle %}{% endblock %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!---<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script> --->
    <link href="https://fonts.googleapis.com/css?family=Dokdo|East+Sea+Dokdo|Nanum+Pen+Script&amp;subset=korean" rel="stylesheet">
    <!---<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}" />

    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.js' %}"></script>--->

	
</head>
<body>
  <div id="header" style=" font-size:100px;font-family: 'East Sea Dokdo',cursive;color:yellow;">
        주 막 보 리 밥
  </div>
    <div id="test1">
      <h1>CSS</h1>
    </div>

<nav class="navbar" >
    
    <ul class="nav navbar-nav" >
      <li class="active" style="font-size:40px;font-family: 'Nanum Pen Script', cursive;"><a href="{% url 'home' %}">주막 보리밥</a></li>
      <li style="font-size:40px;font-family: 'Nanum Pen Script', cursive;"><a href="{% url 'homepage:intro' %}">소 개</a></li>
      <li style="font-size:40px;font-family: 'Nanum Pen Script', cursive;"><a href="{% url 'homepage:dish' %}">메 뉴</a></li>
      <li style="font-size:40px;font-family: 'Nanum Pen Script', cursive;"><a href="{% url 'homepage:photo' %}">사 진 첩</a></li>
    </ul>

</nav>


    
{% block content %}{% endblock %}
{% block footer %}{% endblock %}

</body>
</html>

DONGTAN/templates/home.html
{% extends "base.html" %}

{% block title %}HOME{% endblock %}

{% load staticfiles %}
{% block extrastyle %} {% static "css/home.css" %} {% endblock %}

{% block content %}
<div >

        <img style="width:60%;
        display: block;
        margin-left: auto;
        margin-right: auto;
        border: 1px solid white;
        border-radius: 10px;
        " src="{% static 'img/main.jpg' %}">
      </div>


{% endblock %}

{% block footer %}
<div id="footer" style="padding:30px;text-align: center;font-size: 30px;font-family: 'Nanum Pen Script', cursive;">
	주 소 : 경기도 화성시 동탄면 장지리 834-3 주막보리밥<br>
	전 화 번 호 : 031-374-3104
</div>
{% endblock %}